#! /bin/bash
set -eo pipefail


if ! which flutter > /dev/null; then
  echo "Flutter not found. Please install Flutter before running this script." >&2
  exit 1
fi

# required to upgrade ubuntu base due to incompatible libraries
echo "Updating dependencies..."

sed -i "s/xenial/focal/g" /etc/apt/sources.list
apt-get -qq update
apt-get -qq install -y wget tar unzip zip lib32stdc++6 lib32z1 git clang cmake ninja-build pkg-config libgtk-3-dev curl apt-utils openssl

echo ""
echo "Retrieving application version..."

cd ../../../qaul_ui || exit 1

if [ ! -f pubspec.yaml ]; then
    echo "pubspec.yaml not found!" >&2
    exit 1
fi

VERSION=$(grep "version:" pubspec.yaml | awk '{ print $2 }' | sed 's/+.*$//')
echo "Using App Version: $VERSION"

cd snap || exit

echo ""
echo "Updating app version on snapcraft.yaml and logging into snapcraft..."

# ignore current snap version and set to pubspec version
sed -i "s/^version:.*$/version: $VERSION/g" snapcraft.yaml

if [ -d local ]; then rm -rf local; fi
mkdir local

#openssl aes-256-cbc -d \
#  -in snap_credentials.enc \
#  -out local/snapcraft.login \
#  -k "$SNAPCRAFT_CREDENTIALS_KEY"
echo "$SNAPCRAFT_LOGIN_FILE" | base64 --decode --ignore-garbage > local/snapcraft.login

snapcraft login --with local/snapcraft.login

cd .. || exit 0

echo ""
echo "Building Flutter application..."

git config --global --add safe.directory "$FL_PATH"

snapcraft

mv ./*.snap "qaul-$VERSION.snap"
snapcraft upload "qaul-$VERSION.snap" --release=stable

realpath "qaul-$VERSION.snap"
