name: qaul_components
description: Shared UI components, breakpoints, and design tokens for qaul.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  badges: ^3.1.2
  flutter_svg: ^2.2.3
  unorm_dart: ^0.3.2
  utils: { "path": "../utils" }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/sub_menu/
    - assets/logo/
