// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: services/dtn/dtn_rpc.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package qaul.rpc.dtn;

@kotlin.jvm.JvmName("-initializedTN")
public inline fun dTN(block: qaul.rpc.dtn.DTNKt.Dsl.() -> kotlin.Unit): qaul.rpc.dtn.DtnRpc.DTN =
  qaul.rpc.dtn.DTNKt.Dsl._create(qaul.rpc.dtn.DtnRpc.DTN.newBuilder()).apply { block() }._build()
/**
 * ```
 * DTN service RPC message container
 * ```
 *
 * Protobuf type `qaul.rpc.dtn.DTN`
 */
public object DTNKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.rpc.dtn.DtnRpc.DTN.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.rpc.dtn.DtnRpc.DTN.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.rpc.dtn.DtnRpc.DTN = _builder.build()

    /**
     * ```
     * dtn state request
     * ```
     *
     * `.qaul.rpc.dtn.DtnStateRequest dtn_state_request = 1;`
     */
    public var dtnStateRequest: qaul.rpc.dtn.DtnRpc.DtnStateRequest
      @JvmName("getDtnStateRequest")
      get() = _builder.getDtnStateRequest()
      @JvmName("setDtnStateRequest")
      set(value) {
        _builder.setDtnStateRequest(value)
      }
    /**
     * ```
     * dtn state request
     * ```
     *
     * `.qaul.rpc.dtn.DtnStateRequest dtn_state_request = 1;`
     */
    public fun clearDtnStateRequest() {
      _builder.clearDtnStateRequest()
    }
    /**
     * ```
     * dtn state request
     * ```
     *
     * `.qaul.rpc.dtn.DtnStateRequest dtn_state_request = 1;`
     * @return Whether the dtnStateRequest field is set.
     */
    public fun hasDtnStateRequest(): kotlin.Boolean {
      return _builder.hasDtnStateRequest()
    }

    /**
     * ```
     * dtn state response
     * ```
     *
     * `.qaul.rpc.dtn.DtnStateResponse dtn_state_response = 2;`
     */
    public var dtnStateResponse: qaul.rpc.dtn.DtnRpc.DtnStateResponse
      @JvmName("getDtnStateResponse")
      get() = _builder.getDtnStateResponse()
      @JvmName("setDtnStateResponse")
      set(value) {
        _builder.setDtnStateResponse(value)
      }
    /**
     * ```
     * dtn state response
     * ```
     *
     * `.qaul.rpc.dtn.DtnStateResponse dtn_state_response = 2;`
     */
    public fun clearDtnStateResponse() {
      _builder.clearDtnStateResponse()
    }
    /**
     * ```
     * dtn state response
     * ```
     *
     * `.qaul.rpc.dtn.DtnStateResponse dtn_state_response = 2;`
     * @return Whether the dtnStateResponse field is set.
     */
    public fun hasDtnStateResponse(): kotlin.Boolean {
      return _builder.hasDtnStateResponse()
    }

    /**
     * ```
     * dtn config request
     * ```
     *
     * `.qaul.rpc.dtn.DtnConfigRequest dtn_config_request = 3;`
     */
    public var dtnConfigRequest: qaul.rpc.dtn.DtnRpc.DtnConfigRequest
      @JvmName("getDtnConfigRequest")
      get() = _builder.getDtnConfigRequest()
      @JvmName("setDtnConfigRequest")
      set(value) {
        _builder.setDtnConfigRequest(value)
      }
    /**
     * ```
     * dtn config request
     * ```
     *
     * `.qaul.rpc.dtn.DtnConfigRequest dtn_config_request = 3;`
     */
    public fun clearDtnConfigRequest() {
      _builder.clearDtnConfigRequest()
    }
    /**
     * ```
     * dtn config request
     * ```
     *
     * `.qaul.rpc.dtn.DtnConfigRequest dtn_config_request = 3;`
     * @return Whether the dtnConfigRequest field is set.
     */
    public fun hasDtnConfigRequest(): kotlin.Boolean {
      return _builder.hasDtnConfigRequest()
    }

    /**
     * ```
     * dtn config response
     * ```
     *
     * `.qaul.rpc.dtn.DtnConfigResponse dtn_config_response = 4;`
     */
    public var dtnConfigResponse: qaul.rpc.dtn.DtnRpc.DtnConfigResponse
      @JvmName("getDtnConfigResponse")
      get() = _builder.getDtnConfigResponse()
      @JvmName("setDtnConfigResponse")
      set(value) {
        _builder.setDtnConfigResponse(value)
      }
    /**
     * ```
     * dtn config response
     * ```
     *
     * `.qaul.rpc.dtn.DtnConfigResponse dtn_config_response = 4;`
     */
    public fun clearDtnConfigResponse() {
      _builder.clearDtnConfigResponse()
    }
    /**
     * ```
     * dtn config response
     * ```
     *
     * `.qaul.rpc.dtn.DtnConfigResponse dtn_config_response = 4;`
     * @return Whether the dtnConfigResponse field is set.
     */
    public fun hasDtnConfigResponse(): kotlin.Boolean {
      return _builder.hasDtnConfigResponse()
    }

    /**
     * ```
     * dtn add user request
     * ```
     *
     * `.qaul.rpc.dtn.DtnAddUserRequest dtn_add_user_request = 5;`
     */
    public var dtnAddUserRequest: qaul.rpc.dtn.DtnRpc.DtnAddUserRequest
      @JvmName("getDtnAddUserRequest")
      get() = _builder.getDtnAddUserRequest()
      @JvmName("setDtnAddUserRequest")
      set(value) {
        _builder.setDtnAddUserRequest(value)
      }
    /**
     * ```
     * dtn add user request
     * ```
     *
     * `.qaul.rpc.dtn.DtnAddUserRequest dtn_add_user_request = 5;`
     */
    public fun clearDtnAddUserRequest() {
      _builder.clearDtnAddUserRequest()
    }
    /**
     * ```
     * dtn add user request
     * ```
     *
     * `.qaul.rpc.dtn.DtnAddUserRequest dtn_add_user_request = 5;`
     * @return Whether the dtnAddUserRequest field is set.
     */
    public fun hasDtnAddUserRequest(): kotlin.Boolean {
      return _builder.hasDtnAddUserRequest()
    }

    /**
     * ```
     * dtn add user response
     * ```
     *
     * `.qaul.rpc.dtn.DtnAddUserResponse dtn_add_user_response = 6;`
     */
    public var dtnAddUserResponse: qaul.rpc.dtn.DtnRpc.DtnAddUserResponse
      @JvmName("getDtnAddUserResponse")
      get() = _builder.getDtnAddUserResponse()
      @JvmName("setDtnAddUserResponse")
      set(value) {
        _builder.setDtnAddUserResponse(value)
      }
    /**
     * ```
     * dtn add user response
     * ```
     *
     * `.qaul.rpc.dtn.DtnAddUserResponse dtn_add_user_response = 6;`
     */
    public fun clearDtnAddUserResponse() {
      _builder.clearDtnAddUserResponse()
    }
    /**
     * ```
     * dtn add user response
     * ```
     *
     * `.qaul.rpc.dtn.DtnAddUserResponse dtn_add_user_response = 6;`
     * @return Whether the dtnAddUserResponse field is set.
     */
    public fun hasDtnAddUserResponse(): kotlin.Boolean {
      return _builder.hasDtnAddUserResponse()
    }

    /**
     * ```
     * dtn remove user request
     * ```
     *
     * `.qaul.rpc.dtn.DtnRemoveUserRequest dtn_remove_user_request = 7;`
     */
    public var dtnRemoveUserRequest: qaul.rpc.dtn.DtnRpc.DtnRemoveUserRequest
      @JvmName("getDtnRemoveUserRequest")
      get() = _builder.getDtnRemoveUserRequest()
      @JvmName("setDtnRemoveUserRequest")
      set(value) {
        _builder.setDtnRemoveUserRequest(value)
      }
    /**
     * ```
     * dtn remove user request
     * ```
     *
     * `.qaul.rpc.dtn.DtnRemoveUserRequest dtn_remove_user_request = 7;`
     */
    public fun clearDtnRemoveUserRequest() {
      _builder.clearDtnRemoveUserRequest()
    }
    /**
     * ```
     * dtn remove user request
     * ```
     *
     * `.qaul.rpc.dtn.DtnRemoveUserRequest dtn_remove_user_request = 7;`
     * @return Whether the dtnRemoveUserRequest field is set.
     */
    public fun hasDtnRemoveUserRequest(): kotlin.Boolean {
      return _builder.hasDtnRemoveUserRequest()
    }

    /**
     * ```
     * dtn remove user response
     * ```
     *
     * `.qaul.rpc.dtn.DtnRemoveUserResponse dtn_remove_user_response = 8;`
     */
    public var dtnRemoveUserResponse: qaul.rpc.dtn.DtnRpc.DtnRemoveUserResponse
      @JvmName("getDtnRemoveUserResponse")
      get() = _builder.getDtnRemoveUserResponse()
      @JvmName("setDtnRemoveUserResponse")
      set(value) {
        _builder.setDtnRemoveUserResponse(value)
      }
    /**
     * ```
     * dtn remove user response
     * ```
     *
     * `.qaul.rpc.dtn.DtnRemoveUserResponse dtn_remove_user_response = 8;`
     */
    public fun clearDtnRemoveUserResponse() {
      _builder.clearDtnRemoveUserResponse()
    }
    /**
     * ```
     * dtn remove user response
     * ```
     *
     * `.qaul.rpc.dtn.DtnRemoveUserResponse dtn_remove_user_response = 8;`
     * @return Whether the dtnRemoveUserResponse field is set.
     */
    public fun hasDtnRemoveUserResponse(): kotlin.Boolean {
      return _builder.hasDtnRemoveUserResponse()
    }

    /**
     * ```
     * dtn set total size request
     * ```
     *
     * `.qaul.rpc.dtn.DtnSetTotalSizeRequest dtn_set_total_size_request = 9;`
     */
    public var dtnSetTotalSizeRequest: qaul.rpc.dtn.DtnRpc.DtnSetTotalSizeRequest
      @JvmName("getDtnSetTotalSizeRequest")
      get() = _builder.getDtnSetTotalSizeRequest()
      @JvmName("setDtnSetTotalSizeRequest")
      set(value) {
        _builder.setDtnSetTotalSizeRequest(value)
      }
    /**
     * ```
     * dtn set total size request
     * ```
     *
     * `.qaul.rpc.dtn.DtnSetTotalSizeRequest dtn_set_total_size_request = 9;`
     */
    public fun clearDtnSetTotalSizeRequest() {
      _builder.clearDtnSetTotalSizeRequest()
    }
    /**
     * ```
     * dtn set total size request
     * ```
     *
     * `.qaul.rpc.dtn.DtnSetTotalSizeRequest dtn_set_total_size_request = 9;`
     * @return Whether the dtnSetTotalSizeRequest field is set.
     */
    public fun hasDtnSetTotalSizeRequest(): kotlin.Boolean {
      return _builder.hasDtnSetTotalSizeRequest()
    }

    /**
     * ```
     * dtn set total size response
     * ```
     *
     * `.qaul.rpc.dtn.DtnSetTotalSizeResponse dtn_set_total_size_response = 10;`
     */
    public var dtnSetTotalSizeResponse: qaul.rpc.dtn.DtnRpc.DtnSetTotalSizeResponse
      @JvmName("getDtnSetTotalSizeResponse")
      get() = _builder.getDtnSetTotalSizeResponse()
      @JvmName("setDtnSetTotalSizeResponse")
      set(value) {
        _builder.setDtnSetTotalSizeResponse(value)
      }
    /**
     * ```
     * dtn set total size response
     * ```
     *
     * `.qaul.rpc.dtn.DtnSetTotalSizeResponse dtn_set_total_size_response = 10;`
     */
    public fun clearDtnSetTotalSizeResponse() {
      _builder.clearDtnSetTotalSizeResponse()
    }
    /**
     * ```
     * dtn set total size response
     * ```
     *
     * `.qaul.rpc.dtn.DtnSetTotalSizeResponse dtn_set_total_size_response = 10;`
     * @return Whether the dtnSetTotalSizeResponse field is set.
     */
    public fun hasDtnSetTotalSizeResponse(): kotlin.Boolean {
      return _builder.hasDtnSetTotalSizeResponse()
    }
    public val messageCase: qaul.rpc.dtn.DtnRpc.DTN.MessageCase
      @JvmName("getMessageCase")
      get() = _builder.getMessageCase()

    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.rpc.dtn.DtnRpc.DTN.copy(block: qaul.rpc.dtn.DTNKt.Dsl.() -> kotlin.Unit): qaul.rpc.dtn.DtnRpc.DTN =
  qaul.rpc.dtn.DTNKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnStateRequestOrNull: qaul.rpc.dtn.DtnRpc.DtnStateRequest?
  get() = if (hasDtnStateRequest()) getDtnStateRequest() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnStateResponseOrNull: qaul.rpc.dtn.DtnRpc.DtnStateResponse?
  get() = if (hasDtnStateResponse()) getDtnStateResponse() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnConfigRequestOrNull: qaul.rpc.dtn.DtnRpc.DtnConfigRequest?
  get() = if (hasDtnConfigRequest()) getDtnConfigRequest() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnConfigResponseOrNull: qaul.rpc.dtn.DtnRpc.DtnConfigResponse?
  get() = if (hasDtnConfigResponse()) getDtnConfigResponse() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnAddUserRequestOrNull: qaul.rpc.dtn.DtnRpc.DtnAddUserRequest?
  get() = if (hasDtnAddUserRequest()) getDtnAddUserRequest() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnAddUserResponseOrNull: qaul.rpc.dtn.DtnRpc.DtnAddUserResponse?
  get() = if (hasDtnAddUserResponse()) getDtnAddUserResponse() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnRemoveUserRequestOrNull: qaul.rpc.dtn.DtnRpc.DtnRemoveUserRequest?
  get() = if (hasDtnRemoveUserRequest()) getDtnRemoveUserRequest() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnRemoveUserResponseOrNull: qaul.rpc.dtn.DtnRpc.DtnRemoveUserResponse?
  get() = if (hasDtnRemoveUserResponse()) getDtnRemoveUserResponse() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnSetTotalSizeRequestOrNull: qaul.rpc.dtn.DtnRpc.DtnSetTotalSizeRequest?
  get() = if (hasDtnSetTotalSizeRequest()) getDtnSetTotalSizeRequest() else null

public val qaul.rpc.dtn.DtnRpc.DTNOrBuilder.dtnSetTotalSizeResponseOrNull: qaul.rpc.dtn.DtnRpc.DtnSetTotalSizeResponse?
  get() = if (hasDtnSetTotalSizeResponse()) getDtnSetTotalSizeResponse() else null

