// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: services/dtn/dtn_rpc.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package qaul.rpc.dtn;

@kotlin.jvm.JvmName("-initializedtnConfigRequest")
public inline fun dtnConfigRequest(block: qaul.rpc.dtn.DtnConfigRequestKt.Dsl.() -> kotlin.Unit): qaul.rpc.dtn.DtnRpc.DtnConfigRequest =
  qaul.rpc.dtn.DtnConfigRequestKt.Dsl._create(qaul.rpc.dtn.DtnRpc.DtnConfigRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Dtn Config Request
 * ```
 *
 * Protobuf type `qaul.rpc.dtn.DtnConfigRequest`
 */
public object DtnConfigRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.rpc.dtn.DtnRpc.DtnConfigRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.rpc.dtn.DtnRpc.DtnConfigRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.rpc.dtn.DtnRpc.DtnConfigRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.rpc.dtn.DtnRpc.DtnConfigRequest.copy(block: qaul.rpc.dtn.DtnConfigRequestKt.Dsl.() -> kotlin.Unit): qaul.rpc.dtn.DtnRpc.DtnConfigRequest =
  qaul.rpc.dtn.DtnConfigRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

