// Copyright (c) 2022 Open Community Project Association https://ocpa.ch
// This software is published under the AGPLv3 license.

//! # Qaul GroupChat Service
//!
//! The GroupChat service sends and receives messages and files into group members.
//! The GroupChat messages carry on the Messaging service
//! Messaging(GroupChat(GroupChatContainer(...)))



use libp2p::{
    PeerId,
};

use prost::Message;
use serde::{Deserialize, Serialize};
use sled_extensions::{bincode::Tree, DbExt};
use state::Storage;
use std::collections::BTreeMap;
use std::{
    convert::TryInto,
    sync::RwLock,
};
use crate::node::user_accounts::{UserAccount, UserAccounts};
use crate::rpc::Rpc;
use crate::storage::database::DataBase;
use super::chat::Chat;

use super::messaging::proto;
use super::messaging::Messaging;

mod member;
use member::Member;

mod manage;
use manage::Manage;

mod message;
use message::GroupMessage;


/// Import protobuf message definition generated by
/// the rust module prost-build.
pub mod proto_rpc {
    include!("qaul.rpc.groupchat.rs");
}
pub mod proto_net {
    include!("qaul.net.groupchat.rs");
}


/// Structure to management for groups.
#[derive(Clone)]
pub struct Groups {
    //DB reference 
    pub db_ref: Tree<Group>,
    // last group index
    pub last_group: u64,
    // id mapping group_id => index in DB
    pub group_ids: BTreeMap<Vec<u8>, u64>,
}


impl Groups{
    pub fn group_id_to_index(&self, group_id: &Vec<u8>) -> u64{        
        if self.group_ids.contains_key(group_id){
            return *self.group_ids.get(group_id).unwrap();
        }
        return 0;
    }    
}

/// Structure of user => groups mapping for storage
pub struct GroupsOfUser {
    pub groups_of_user: BTreeMap<Vec<u8>, Groups>,
}

/// Structure of group member
#[derive(Serialize, Deserialize, Clone)]
pub struct GroupMember {    
    // user id
    pub user_id: Vec<u8>,
    // role = 0 => member, 255 => admin
    pub role: u8,
    // joined at
    pub joined_at: u64,
    // state for future using
    pub state: u8,
}

/// Structure of Group
#[derive(Serialize, Deserialize, Clone)]
pub struct Group {
    // group id
    pub id: Vec<u8>,
    // group name
    pub name: String,
    // created at
    pub created_at: u64,
    // creator id
    pub creator_id: Vec<u8>,
    // members
    pub members: BTreeMap<Vec<u8>, GroupMember>,
}

impl Group{
    pub fn get_member(&self, user_id: &Vec<u8>)-> Option<&GroupMember>{
        if self.members.contains_key(user_id){
            return self.members.get(user_id);
        }
        None
    }
}

/// mutable state of all user groups
pub static GROUPSOFUSER: Storage<RwLock<GroupsOfUser>> = Storage::new();

pub struct GroupChat{
}

/// GroupChat module to process transfer, receive and RPC commands
impl GroupChat {
    /// initialize group chat module
    pub fn init() {
        let groups_of_user = GroupsOfUser{
            groups_of_user: BTreeMap::new(),
        };
        GROUPSOFUSER.set(RwLock::new(groups_of_user));
    }

    /// get group name
    pub fn get_group_name(user_id: PeerId, group_id: &Vec<u8>) -> Option<String>{
        let groups_of_user = GROUPSOFUSER.get().read().unwrap();
        if !groups_of_user.groups_of_user.contains_key(&user_id.to_bytes()){
            return None;
        }

        let groups = groups_of_user.groups_of_user.get(&user_id.to_bytes()).unwrap();
        let idx = groups.group_id_to_index(group_id);
        if idx == 0{
            return None;
        }
        if let Ok(res) = groups.db_ref.get(&idx.to_be_bytes()){
            match res{
                Some(group) =>{
                    return Some(group.name.clone());
                },
                _ =>{

                }
            }
        }
        None        
    }

    /// update user's groups
    pub fn update_groups_of_user(user_id: PeerId, groups: Groups){
        let mut groups_of_user = GROUPSOFUSER.get().write().unwrap();
        groups_of_user.groups_of_user.insert(user_id.to_bytes(), groups);
    }

    /// get user's groups
    pub fn get_groups_of_user(user_id: PeerId) ->Groups{
        let mut groups_of_user = GROUPSOFUSER.get().write().unwrap();
        if !groups_of_user.groups_of_user.contains_key(&user_id.to_bytes()){
            let new_groups_of_user = Self::create_groups_of_user(user_id);
            groups_of_user.groups_of_user.insert(user_id.to_bytes(), new_groups_of_user);            
        }
        let groups = groups_of_user.groups_of_user.get(&user_id.to_bytes()).unwrap();
        groups.clone()
    }

    /// create new user's groups from DB
    fn create_groups_of_user(user_id: PeerId) -> Groups{
        let db = DataBase::get_user_db(user_id);
        let tree: Tree<Group> = db.open_bincode_tree("groups").unwrap();

        // // get last key
        let last_group: u64;
        match tree.iter().last() {
            Some(Ok((ivec, _))) => {
                let i = ivec.to_vec();
                match i.try_into() {
                    Ok(arr) => {
                        last_group = u64::from_be_bytes(arr);
                    }
                    Err(e) => {
                        log::error!("couldn't convert ivec to u64: {:?}", e);
                        last_group = 0;
                    }    
                }
            },
            None => {
                last_group = 0;
            },
            Some(Err(e)) => {
                log::error!("Sled feed table error: {}", e);
                last_group = 0;
            }
        }

        let mut ids: BTreeMap<Vec<u8>, u64> =  BTreeMap::new();
        //initialize group_id mapping
        for res in tree.iter(){
            match res {
                Ok((idx, group)) => {
                    let index = idx.to_vec();
                    ids.insert(group.id, u64::from_be_bytes(index.try_into().unwrap()));
                },
                Err(e) => {
                    log::error!("Error retrieving feed message from data base: {}", e);
                }
            }
        }

        let groups = Groups{
            db_ref: tree,
            last_group,
            group_ids: ids,
        };
        groups
    }


    /// Send capsuled group message through messaging service
    pub fn send_group_message_through_message(user_account: &UserAccount, receiver:PeerId, data: &Vec<u8>){
        let snd_message = proto::Messaging{
            message: Some(proto::messaging::Message::GroupChatMessage(
                proto::GroupChatMessage{
                    content: data.to_vec(),
                }
            )),
        };
        let mut message_buf00 = Vec::with_capacity(snd_message.encoded_len());
        snd_message
            .encode(&mut message_buf00)
            .expect("Vec<u8> provides capacity as needed");
        log::info!("message_buf len {}", message_buf00.len());

        // send message via messaging
        if let Err(e) = Messaging::pack_and_send_message(user_account, receiver, message_buf00) {
            log::error!("group message sending failed {}", e.to_string());
        }
    }

    /// BroadCast group updated to all members
    fn post_group_update(my_user_id: &PeerId, group_id: &Vec<u8>){
        let groups = Self::get_groups_of_user(my_user_id.clone());

        let group_idx = groups.group_id_to_index(group_id);
        if group_idx == 0{
            return;
        }

        let group = groups.db_ref.get(&group_idx.to_be_bytes()).unwrap().unwrap();

        //create group notify messge and post to all members        
        let mut members: Vec<proto_net::Member> = vec![];
        for m in group.members.values(){
            members.push(proto_net::Member{
                user_id: m.user_id.clone(),
                role: m.role as u32,
                state: m.state as u32,
                joined_at: m.joined_at,
            });
        }

        let proto_message = proto_net::GroupChatContainer {
            message: Some(proto_net::group_chat_container::Message::Notify(
                proto_net::GroupNotify {
                    group_id: group_id.clone(),
                    group_name: group.name.clone(),
                    created_at: group.created_at,
                    creator_id: group.creator_id.clone(),
                    members,
                },
            )),
        };

        let mut message_buff = Vec::with_capacity(proto_message.encoded_len());
        proto_message
            .encode(&mut message_buff)
            .expect("Vec<u8> provides capacity as needed");

        //broad cast to all group members
        if let Some(user_account) = UserAccounts::get_by_id(*my_user_id){
            for user_id in group.members.keys(){
                let receiver = PeerId::from_bytes(&user_id.clone()).unwrap();
                if receiver != *my_user_id{
                    Self::send_group_message_through_message(&user_account, receiver, &message_buff);
                }                
            }
        }

    }

    /// Process incoming NET messages for group chat module
    pub fn net(sender_id: PeerId, receiver_id: PeerId, data: Vec<u8>, signature: Vec<u8>){
        //check receiver id is in users list
        let user;
        match UserAccounts::get_by_id(receiver_id) {
            Some(usr) => {
                user = usr;
            }
            None => {
                log::error!("no user id={}", receiver_id);
                return;
            }
        }

        match proto_net::GroupChatContainer::decode(&data[..]) {
            Ok(messaging) =>{
                match messaging.message{
                    Some(proto_net::group_chat_container::Message::InviteMember(invite_member)) => {
                        log::info!("groupchat::on_receive_invite");
                        Member::on_be_invited(&user, &sender_id, &receiver_id, &invite_member, signature);
                    },
                    Some(proto_net::group_chat_container::Message::Removed(_removed)) => {
                        log::info!("groupchat::on_removed");
                    },
                    Some(proto_net::group_chat_container::Message::ReplyInvite(reply_invite)) => {
                        log::info!("groupchat::on_answered for invite");
                        if let Err(error) =  Member::on_reply_invite(&sender_id, &receiver_id, &reply_invite, signature){
                            log::error!("groupchat on_reply_invite error {}", error);
                        }else {
                            if reply_invite.accept{
                                Self::post_group_update(&user.id, &reply_invite.group_id);
                            }                            
                        }
                    },
                    Some(proto_net::group_chat_container::Message::Notify(notify)) => {
                        log::info!("groupchat::on_notify");
                        Manage::on_group_notify(&sender_id.to_bytes(), &receiver_id.to_bytes(), &notify);
                    },
                    Some(proto_net::group_chat_container::Message::GroupchatMessage(chat_message)) => {
                        log::info!("groupchat::on_received_chat_message");
                        if let Err(error) = GroupMessage::on_message(&sender_id.to_bytes(), &receiver_id.to_bytes(), &chat_message, signature){
                            log::error!("GroupMessage::on_message {}", error.to_string());
                        }
                    },
                    None => {
                        log::error!("file share message from {} was empty", sender_id.to_base58())
                    },                    
                }
            },
            Err(e) => {
                log::error!(
                    "Error decoding FileSharing Message from {} to {}: {}",
                    sender_id.to_base58(),
                    receiver_id.to_base58(),
                    e
                );
            }
        }

    }

    /// Process incoming RPC request messages for group chat module
    pub fn rpc(data: Vec<u8>, user_id: Vec<u8>) {
        let my_user_id = PeerId::from_bytes(&user_id).unwrap();

        match proto_rpc::GroupChatRpc::decode(&data[..]) {
            Ok(groupchat_rpc) => {
                match groupchat_rpc.message {
                    Some(proto_rpc::group_chat_rpc::Message::GroupCreateRequest(group_create_req)) => {
                        let id = Manage::create_new_group(&my_user_id, group_create_req.group_name.clone());
                        //make response
                        let proto_message = proto_rpc::GroupChatRpc {
                            message: Some(proto_rpc::group_chat_rpc::Message::GroupCreateResponse(
                                proto_rpc::GroupCreateResponse {
                                    group_name: group_create_req.group_name.clone(),
                                    group_id: id,
                                },
                            )),
                        };

                        // encode message
                        let mut buf = Vec::with_capacity(proto_message.encoded_len());
                        proto_message
                            .encode(&mut buf)
                            .expect("Vec<u8> provides capacity as needed");

                        // send message
                        Rpc::send_message(
                            buf,
                            crate::rpc::proto::Modules::Groupchat.into(),
                            "".to_string(),
                            Vec::new(),
                        );                    
                    },
                    Some(proto_rpc::group_chat_rpc::Message::GroupRenameRequest(group_rename_req)) => {
                        if let Err(err) = Manage::rename_group(&my_user_id, &group_rename_req.group_id, group_rename_req.group_name.clone()){
                            log::error!("Rename group error, {}", err);
                        }else{
                            let proto_message = proto_rpc::GroupChatRpc {
                                message: Some(proto_rpc::group_chat_rpc::Message::GroupCreateResponse(
                                    proto_rpc::GroupCreateResponse {
                                        group_name: group_rename_req.group_name.clone(),
                                        group_id: group_rename_req.group_id.clone(),
                                    },
                                )),
                            };
    
                            // encode message
                            let mut buf = Vec::with_capacity(proto_message.encoded_len());
                            proto_message
                                .encode(&mut buf)
                                .expect("Vec<u8> provides capacity as needed");
    
                            // send message
                            Rpc::send_message(
                                buf,
                                crate::rpc::proto::Modules::Groupchat.into(),
                                "".to_string(),
                                Vec::new(),
                            );

                            //post updates
                            Self::post_group_update(&my_user_id, &group_rename_req.group_id);
                        }
                    },
                    Some(proto_rpc::group_chat_rpc::Message::GroupInfoRequest(group_info_req)) => {
                        match Manage::group_info(&my_user_id, &group_info_req.group_id) {
                            Ok(res)=>{
                                let proto_message = proto_rpc::GroupChatRpc {
                                    message: Some(proto_rpc::group_chat_rpc::Message::GroupInfoResponse(
                                        res
                                    )),
                                };        
                                // encode message
                                let mut buf = Vec::with_capacity(proto_message.encoded_len());
                                proto_message
                                    .encode(&mut buf)
                                    .expect("Vec<u8> provides capacity as needed");
        
                                // send message
                                Rpc::send_message(
                                    buf,
                                    crate::rpc::proto::Modules::Groupchat.into(),
                                    "".to_string(),
                                    Vec::new(),
                                );    
                            },
                            Err(err) =>{
                                log::error!("Get group info error, {}", err);
                            }
                        }
                    },
                    Some(proto_rpc::group_chat_rpc::Message::GroupListRequest(_group_list_req)) => {
                        let list = Manage::group_list(&my_user_id);
                        let proto_message = proto_rpc::GroupChatRpc {
                            message: Some(proto_rpc::group_chat_rpc::Message::GroupListResponse(
                                list
                            )),
                        };        
                        // encode message
                        let mut buf = Vec::with_capacity(proto_message.encoded_len());
                        proto_message
                            .encode(&mut buf)
                            .expect("Vec<u8> provides capacity as needed");

                        // send message
                        Rpc::send_message(
                            buf,
                            crate::rpc::proto::Modules::Groupchat.into(),
                            "".to_string(),
                            Vec::new(),
                        );
                    },
                    Some(proto_rpc::group_chat_rpc::Message::GroupInviteMemberRequest(invite_req)) => {                       
                        if let Err(err) =  Member::invite(&my_user_id, &invite_req.group_id, &invite_req.user_id) {
                            log::error!("Get group info error, {}", err);
                        }
                    },
                    Some(proto_rpc::group_chat_rpc::Message::GroupReplyInviteRequest(reply_req)) => {
                        if let Err(err) =  Member::reply_invite(&my_user_id, &reply_req.group_id, &reply_req.user_id, reply_req.accept) {
                            log::error!("Get group info error, {}", err);
                        }
                    },                   

                    Some(proto_rpc::group_chat_rpc::Message::GroupRemoveMemberRequest(remove_req)) => {                       
                        if let Err(err) =  Member::remove(&my_user_id, &remove_req.group_id, &remove_req.user_id) {
                            log::error!("Get group info error, {}", err);
                        }else{
                            Self::post_group_update(&my_user_id, &remove_req.group_id);
                        }
                    },
                    Some(proto_rpc::group_chat_rpc::Message::GroupSendRequest(send_req)) => {                       
                        if let Err(err) =  GroupMessage::send(&my_user_id, &send_req.group_id, send_req.message.clone()) {
                            log::error!("Get group send error, {}", err);
                        }
                    },                    
                    _ => {
                        log::error!("Unhandled Protobuf Group chat message");
                    }
                }
            }
            Err(error) => {
                log::error!("{:?}", error);
            }
        }
    }

}
