// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: router/router_net_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package qaul.net.router_net_info;

@kotlin.jvm.JvmName("-initializerouterInfoContent")
public inline fun routerInfoContent(block: qaul.net.router_net_info.RouterInfoContentKt.Dsl.() -> kotlin.Unit): qaul.net.router_net_info.RouterNetInfo.RouterInfoContent =
  qaul.net.router_net_info.RouterInfoContentKt.Dsl._create(qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.newBuilder()).apply { block() }._build()
/**
 * ```
 * Router information content
 * ```
 *
 * Protobuf type `qaul.net.router_net_info.RouterInfoContent`
 */
public object RouterInfoContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.net.router_net_info.RouterNetInfo.RouterInfoContent = _builder.build()

    /**
     * ```
     * node id
     * ```
     *
     * `bytes id = 1;`
     */
    public var id: com.google.protobuf.ByteString
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * node id
     * ```
     *
     * `bytes id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * RouterInfo Module
     * ```
     *
     * `.qaul.net.router_net_info.RouterInfoModule routerInfoModule = 2;`
     */
    public var routerInfoModule: qaul.net.router_net_info.RouterNetInfo.RouterInfoModule
      @JvmName("getRouterInfoModule")
      get() = _builder.getRouterInfoModule()
      @JvmName("setRouterInfoModule")
      set(value) {
        _builder.setRouterInfoModule(value)
      }
    public var routerInfoModuleValue: kotlin.Int
      @JvmName("getRouterInfoModuleValue")
      get() = _builder.getRouterInfoModuleValue()
      @JvmName("setRouterInfoModuleValue")
      set(value) {
        _builder.setRouterInfoModuleValue(value)
      }
    /**
     * ```
     * RouterInfo Module
     * ```
     *
     * `.qaul.net.router_net_info.RouterInfoModule routerInfoModule = 2;`
     */
    public fun clearRouterInfoModule() {
      _builder.clearRouterInfoModule()
    }

    /**
     * ```
     * message content
     * ```
     *
     * `bytes content = 3;`
     */
    public var content: com.google.protobuf.ByteString
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * ```
     * message content
     * ```
     *
     * `bytes content = 3;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * ```
     * timestamp in milli seconds
     * ```
     *
     * `uint64 time = 4;`
     */
    public var time: kotlin.Long
      @JvmName("getTime")
      get() = _builder.getTime()
      @JvmName("setTime")
      set(value) {
        _builder.setTime(value)
      }
    /**
     * ```
     * timestamp in milli seconds
     * ```
     *
     * `uint64 time = 4;`
     */
    public fun clearTime() {
      _builder.clearTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.copy(block: qaul.net.router_net_info.RouterInfoContentKt.Dsl.() -> kotlin.Unit): qaul.net.router_net_info.RouterNetInfo.RouterInfoContent =
  qaul.net.router_net_info.RouterInfoContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

