//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: router/router_net_info.proto

package qaul.net.router_net_info;

@kotlin.jvm.JvmName("-initializerouterInfoContent")
public inline fun routerInfoContent(block: qaul.net.router_net_info.RouterInfoContentKt.Dsl.() -> kotlin.Unit): qaul.net.router_net_info.RouterNetInfo.RouterInfoContent =
  qaul.net.router_net_info.RouterInfoContentKt.Dsl._create(qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.newBuilder()).apply { block() }._build()
public object RouterInfoContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.net.router_net_info.RouterNetInfo.RouterInfoContent = _builder.build()

    /**
     * <pre>
     * node id
     * </pre>
     *
     * <code>bytes id = 1;</code>
     */
    public var id: com.google.protobuf.ByteString
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <pre>
     * node id
     * </pre>
     *
     * <code>bytes id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <pre>
     * message content
     * </pre>
     *
     * <code>bytes content = 2;</code>
     */
    public var content: com.google.protobuf.ByteString
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <pre>
     * message content
     * </pre>
     *
     * <code>bytes content = 2;</code>
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * <pre>
     * timestamp in milli seconds
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    public var time: kotlin.Long
      @JvmName("getTime")
      get() = _builder.getTime()
      @JvmName("setTime")
      set(value) {
        _builder.setTime(value)
      }
    /**
     * <pre>
     * timestamp in milli seconds
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    public fun clearTime() {
      _builder.clearTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.net.router_net_info.RouterNetInfo.RouterInfoContent.copy(block: qaul.net.router_net_info.RouterInfoContentKt.Dsl.() -> kotlin.Unit): qaul.net.router_net_info.RouterNetInfo.RouterInfoContent =
  qaul.net.router_net_info.RouterInfoContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

