update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    if is_ci?
        xcversion(version: "13.0")
    end
  end

  desc "Upload to Testflight"
  lane :upload_testflight do
    # Generate hash used for JWT authentication
    api_key = app_store_connect_api_key

    # Get the version number from the project and check against
    # the latest build already available on TestFlight, then
    # increase the build number by 1. If no build is available
    # for that version, then start at 1
    increment_build_number(
      build_number: latest_testflight_build_number(
        api_key: api_key,
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "Runner.xcodeproj")
      ) + 1,
    )

    # Set up Distribution code signing and build the app
    match(type: "appstore")
    gym(scheme: "Runner")

    # Upload the binary to TestFlight and automatically publish
    # to the configured beta testing group
    pilot(
      distribute_external: true,
      notify_external_testers: true,
      groups: ["App Store Connect Users"],
      changelog: "New build by CircleCI"
    )
  end
end
