update_fastlane

default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end

  desc "Deploy a new beta build to Google Play"
  lane :upload_beta_playstore do
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
    upload_to_play_store(track: 'internal', release_status: 'draft', aab: '../build/app/outputs/bundle/release/app-release.aab')
  end
end
