[package]
name = "libqaul-rpc"
description = "libqaul rpc structures and utilities"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>", "jess 3jane <me@jess.coffee>"]
edition = "2018"

[features]
default = ["proto", "json", "chat", "files", "voice"]
proto = ["capnp"]
json = ["serde_json"]
chat = ["qaul-chat"]
files = ["qaul-files"]
voice = ["qaul-voice"]

[dependencies]
qaul-chat = { path = "../service/chat", optional = true }
qaul-files = { path = "../service/files", optional = true }
qaul-voice = { path = "../service/voice", optional = true }

libqaul = { version = "*", path = ".." }
capnp = { version = "0.12", optional = true }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = [ "derive" ] }
async-trait = "0.1"
async-std = { version = "=1.5", features = ["attributes"]}
futures = "0.3"
failure = "0.1"
crossbeam-queue = "0.2"

[dev-dependencies]
conjoiner-engine = "1.2"
ratman = { path = "../../ratman" }
ratman-harness = { path = "../../ratman/harness" }
tempfile = "3.0"

