// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: connections/connections.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package qaul.rpc.connections;

@kotlin.jvm.JvmName("-initializeinternetNodesRequest")
public inline fun internetNodesRequest(block: qaul.rpc.connections.InternetNodesRequestKt.Dsl.() -> kotlin.Unit): qaul.rpc.connections.ConnectionsOuterClass.InternetNodesRequest =
  qaul.rpc.connections.InternetNodesRequestKt.Dsl._create(qaul.rpc.connections.ConnectionsOuterClass.InternetNodesRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * UI request for Internet nodes list
 * ```
 *
 * Protobuf type `qaul.rpc.connections.InternetNodesRequest`
 */
public object InternetNodesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.rpc.connections.ConnectionsOuterClass.InternetNodesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.rpc.connections.ConnectionsOuterClass.InternetNodesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.rpc.connections.ConnectionsOuterClass.InternetNodesRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.rpc.connections.ConnectionsOuterClass.InternetNodesRequest.copy(block: qaul.rpc.connections.InternetNodesRequestKt.Dsl.() -> kotlin.Unit): qaul.rpc.connections.ConnectionsOuterClass.InternetNodesRequest =
  qaul.rpc.connections.InternetNodesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

