//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: router/router.proto

package qaul.rpc.router;

@kotlin.jvm.JvmSynthetic
public inline fun connectionEntry(block: qaul.rpc.router.ConnectionEntryKt.Dsl.() -> kotlin.Unit): qaul.rpc.router.RouterOuterClass.ConnectionEntry =
  qaul.rpc.router.ConnectionEntryKt.Dsl._create(qaul.rpc.router.RouterOuterClass.ConnectionEntry.newBuilder()).apply { block() }._build()
public object ConnectionEntryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.rpc.router.RouterOuterClass.ConnectionEntry.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.rpc.router.RouterOuterClass.ConnectionEntry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.rpc.router.RouterOuterClass.ConnectionEntry = _builder.build()

    /**
     * <pre>
     * round trip time in milli seconds
     * </pre>
     *
     * <code>uint32 rtt = 1;</code>
     */
    public var rtt: kotlin.Int
      @JvmName("getRtt")
      get() = _builder.getRtt()
      @JvmName("setRtt")
      set(value) {
        _builder.setRtt(value)
      }
    /**
     * <pre>
     * round trip time in milli seconds
     * </pre>
     *
     * <code>uint32 rtt = 1;</code>
     */
    public fun clearRtt() {
      _builder.clearRtt()
    }

    /**
     * <pre>
     * hop count to the user.
     * This represents the number of nodes between this node and the user.
     * </pre>
     *
     * <code>uint32 hop_count = 2;</code>
     */
    public var hopCount: kotlin.Int
      @JvmName("getHopCount")
      get() = _builder.getHopCount()
      @JvmName("setHopCount")
      set(value) {
        _builder.setHopCount(value)
      }
    /**
     * <pre>
     * hop count to the user.
     * This represents the number of nodes between this node and the user.
     * </pre>
     *
     * <code>uint32 hop_count = 2;</code>
     */
    public fun clearHopCount() {
      _builder.clearHopCount()
    }

    /**
     * <pre>
     * connection can be established via the node with the following id
     * </pre>
     *
     * <code>bytes via = 3;</code>
     */
    public var via: com.google.protobuf.ByteString
      @JvmName("getVia")
      get() = _builder.getVia()
      @JvmName("setVia")
      set(value) {
        _builder.setVia(value)
      }
    /**
     * <pre>
     * connection can be established via the node with the following id
     * </pre>
     *
     * <code>bytes via = 3;</code>
     */
    public fun clearVia() {
      _builder.clearVia()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.rpc.router.RouterOuterClass.ConnectionEntry.copy(block: qaul.rpc.router.ConnectionEntryKt.Dsl.() -> kotlin.Unit): qaul.rpc.router.RouterOuterClass.ConnectionEntry =
  qaul.rpc.router.ConnectionEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()
