//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: router/router.proto

package qaul.rpc.router;

@kotlin.jvm.JvmSynthetic
inline fun neighboursList(block: qaul.rpc.router.NeighboursListKt.Dsl.() -> Unit): qaul.rpc.router.RouterOuterClass.NeighboursList =
  qaul.rpc.router.NeighboursListKt.Dsl._create(qaul.rpc.router.RouterOuterClass.NeighboursList.newBuilder()).apply { block() }._build()
object NeighboursListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: qaul.rpc.router.RouterOuterClass.NeighboursList.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.rpc.router.RouterOuterClass.NeighboursList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.rpc.router.RouterOuterClass.NeighboursList = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class LanProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .qaul.rpc.router.NeighboursEntry lan = 1;</code>
     */
     val lan: com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, LanProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getLanList()
      )
    /**
     * <code>repeated .qaul.rpc.router.NeighboursEntry lan = 1;</code>
     * @param value The lan to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addLan")
    fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, LanProxy>.add(value: qaul.rpc.router.RouterOuterClass.NeighboursEntry) {
      _builder.addLan(value)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry lan = 1;</code>
     * @param value The lan to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignLan")
    inline operator fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, LanProxy>.plusAssign(value: qaul.rpc.router.RouterOuterClass.NeighboursEntry) {
      add(value)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry lan = 1;</code>
     * @param values The lan to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllLan")
    fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, LanProxy>.addAll(values: kotlin.collections.Iterable<qaul.rpc.router.RouterOuterClass.NeighboursEntry>) {
      _builder.addAllLan(values)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry lan = 1;</code>
     * @param values The lan to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllLan")
    inline operator fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, LanProxy>.plusAssign(values: kotlin.collections.Iterable<qaul.rpc.router.RouterOuterClass.NeighboursEntry>) {
      addAll(values)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry lan = 1;</code>
     * @param index The index to set the value at.
     * @param value The lan to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setLan")
    operator fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, LanProxy>.set(index: kotlin.Int, value: qaul.rpc.router.RouterOuterClass.NeighboursEntry) {
      _builder.setLan(index, value)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry lan = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearLan")
    fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, LanProxy>.clear() {
      _builder.clearLan()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class InternetProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .qaul.rpc.router.NeighboursEntry internet = 2;</code>
     */
     val internet: com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, InternetProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getInternetList()
      )
    /**
     * <code>repeated .qaul.rpc.router.NeighboursEntry internet = 2;</code>
     * @param value The internet to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addInternet")
    fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, InternetProxy>.add(value: qaul.rpc.router.RouterOuterClass.NeighboursEntry) {
      _builder.addInternet(value)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry internet = 2;</code>
     * @param value The internet to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignInternet")
    inline operator fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, InternetProxy>.plusAssign(value: qaul.rpc.router.RouterOuterClass.NeighboursEntry) {
      add(value)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry internet = 2;</code>
     * @param values The internet to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllInternet")
    fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, InternetProxy>.addAll(values: kotlin.collections.Iterable<qaul.rpc.router.RouterOuterClass.NeighboursEntry>) {
      _builder.addAllInternet(values)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry internet = 2;</code>
     * @param values The internet to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllInternet")
    inline operator fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, InternetProxy>.plusAssign(values: kotlin.collections.Iterable<qaul.rpc.router.RouterOuterClass.NeighboursEntry>) {
      addAll(values)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry internet = 2;</code>
     * @param index The index to set the value at.
     * @param value The internet to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setInternet")
    operator fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, InternetProxy>.set(index: kotlin.Int, value: qaul.rpc.router.RouterOuterClass.NeighboursEntry) {
      _builder.setInternet(index, value)
    }/**
     * <code>repeated .qaul.rpc.router.NeighboursEntry internet = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearInternet")
    fun com.google.protobuf.kotlin.DslList<qaul.rpc.router.RouterOuterClass.NeighboursEntry, InternetProxy>.clear() {
      _builder.clearInternet()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun qaul.rpc.router.RouterOuterClass.NeighboursList.copy(block: qaul.rpc.router.NeighboursListKt.Dsl.() -> Unit): qaul.rpc.router.RouterOuterClass.NeighboursList =
  qaul.rpc.router.NeighboursListKt.Dsl._create(this.toBuilder()).apply { block() }._build()
