
platform :mac do
    before_all do
        setup_circle_ci
        import_certificate(
          keychain_name: "qaul-keychain",
          keychain_password: "$KEYCHAIN_PASSWORD",
          certificate_path: 'Certificates.cer',
          certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default"
        )
    end

    lane :release_ci do
        #sh("xcrun", "notarytool", "store-credentials", "NOTARY_PASSWORD", "--apple-id", "$NOTARYTOOL_USERNAME", "--team-id", "$NOTARYTOOL_TEAM_ID", "--password", "$NOTARYTOOL_PASSWORD")
        sh "xcrun notarytool store-credentials NOTARY_PASSWORD --apple-id \"$NOTARYTOOL_USERNAME\" --team-id \"$NOTARYTOOL_TEAM_ID\" --password \"$NOTARYTOOL_PASSWORD\""
        Dir.chdir "../../../utilities/installers/macos/bin" do
            sh("./dmgbuild")
        end
    end
end
