// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: connections/ble/ble_net.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package qaul.net.ble;

@kotlin.jvm.JvmName("-initializeidentification")
public inline fun identification(block: qaul.net.ble.IdentificationKt.Dsl.() -> kotlin.Unit): qaul.net.ble.BleNet.Identification =
  qaul.net.ble.IdentificationKt.Dsl._create(qaul.net.ble.BleNet.Identification.newBuilder()).apply { block() }._build()
/**
 * ```
 * Identfication Request
 * ```
 *
 * Protobuf type `qaul.net.ble.Identification`
 */
public object IdentificationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.net.ble.BleNet.Identification.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.net.ble.BleNet.Identification.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.net.ble.BleNet.Identification = _builder.build()

    /**
     * `bool request = 1;`
     */
    public var request: kotlin.Boolean
      @JvmName("getRequest")
      get() = _builder.getRequest()
      @JvmName("setRequest")
      set(value) {
        _builder.setRequest(value)
      }
    /**
     * `bool request = 1;`
     */
    public fun clearRequest() {
      _builder.clearRequest()
    }

    /**
     * `.qaul.net.ble.NodeIdentification node = 2;`
     */
    public var node: qaul.net.ble.BleNet.NodeIdentification
      @JvmName("getNode")
      get() = _builder.getNode()
      @JvmName("setNode")
      set(value) {
        _builder.setNode(value)
      }
    /**
     * `.qaul.net.ble.NodeIdentification node = 2;`
     */
    public fun clearNode() {
      _builder.clearNode()
    }
    /**
     * `.qaul.net.ble.NodeIdentification node = 2;`
     * @return Whether the node field is set.
     */
    public fun hasNode(): kotlin.Boolean {
      return _builder.hasNode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.net.ble.BleNet.Identification.copy(block: qaul.net.ble.IdentificationKt.Dsl.() -> kotlin.Unit): qaul.net.ble.BleNet.Identification =
  qaul.net.ble.IdentificationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val qaul.net.ble.BleNet.IdentificationOrBuilder.nodeOrNull: qaul.net.ble.BleNet.NodeIdentification?
  get() = if (hasNode()) getNode() else null

