//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: connections/ble/ble.proto

package qaul.sys.ble;

@kotlin.jvm.JvmName("-initializebleDirectReceived")
public inline fun bleDirectReceived(block: qaul.sys.ble.BleDirectReceivedKt.Dsl.() -> kotlin.Unit): qaul.sys.ble.BleOuterClass.BleDirectReceived =
  qaul.sys.ble.BleDirectReceivedKt.Dsl._create(qaul.sys.ble.BleOuterClass.BleDirectReceived.newBuilder()).apply { block() }._build()
public object BleDirectReceivedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.sys.ble.BleOuterClass.BleDirectReceived.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.sys.ble.BleOuterClass.BleDirectReceived.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.sys.ble.BleOuterClass.BleDirectReceived = _builder.build()

    /**
     * <pre>
     * qaul id of the sending device
     * </pre>
     *
     * <code>bytes from = 1;</code>
     */
    public var from: com.google.protobuf.ByteString
      @JvmName("getFrom")
      get() = _builder.getFrom()
      @JvmName("setFrom")
      set(value) {
        _builder.setFrom(value)
      }
    /**
     * <pre>
     * qaul id of the sending device
     * </pre>
     *
     * <code>bytes from = 1;</code>
     */
    public fun clearFrom() {
      _builder.clearFrom()
    }

    /**
     * <pre>
     * the data received
     * </pre>
     *
     * <code>bytes data = 4;</code>
     */
    public var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <pre>
     * the data received
     * </pre>
     *
     * <code>bytes data = 4;</code>
     */
    public fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.sys.ble.BleOuterClass.BleDirectReceived.copy(block: qaul.sys.ble.BleDirectReceivedKt.Dsl.() -> kotlin.Unit): qaul.sys.ble.BleOuterClass.BleDirectReceived =
  qaul.sys.ble.BleDirectReceivedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

