//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: connections/ble/manager/ble.proto

package qaul.sys.ble;

@kotlin.jvm.JvmSynthetic
public inline fun bleInfoResponse(block: qaul.sys.ble.BleInfoResponseKt.Dsl.() -> kotlin.Unit): qaul.sys.ble.BleOuterClass.BleInfoResponse =
  qaul.sys.ble.BleInfoResponseKt.Dsl._create(qaul.sys.ble.BleOuterClass.BleInfoResponse.newBuilder()).apply { block() }._build()
public object BleInfoResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.sys.ble.BleOuterClass.BleInfoResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.sys.ble.BleOuterClass.BleInfoResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.sys.ble.BleOuterClass.BleInfoResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DeviceProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * fill in a device information for each device on the system
     * </pre>
     *
     * <code>repeated .qaul.sys.ble.BleDeviceInfo device = 1;</code>
     */
     public val device: com.google.protobuf.kotlin.DslList<qaul.sys.ble.BleOuterClass.BleDeviceInfo, DeviceProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDeviceList()
      )
    /**
     * <pre>
     * fill in a device information for each device on the system
     * </pre>
     *
     * <code>repeated .qaul.sys.ble.BleDeviceInfo device = 1;</code>
     * @param value The device to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDevice")
    public fun com.google.protobuf.kotlin.DslList<qaul.sys.ble.BleOuterClass.BleDeviceInfo, DeviceProxy>.add(value: qaul.sys.ble.BleOuterClass.BleDeviceInfo) {
      _builder.addDevice(value)
    }/**
     * <pre>
     * fill in a device information for each device on the system
     * </pre>
     *
     * <code>repeated .qaul.sys.ble.BleDeviceInfo device = 1;</code>
     * @param value The device to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDevice")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<qaul.sys.ble.BleOuterClass.BleDeviceInfo, DeviceProxy>.plusAssign(value: qaul.sys.ble.BleOuterClass.BleDeviceInfo) {
      add(value)
    }/**
     * <pre>
     * fill in a device information for each device on the system
     * </pre>
     *
     * <code>repeated .qaul.sys.ble.BleDeviceInfo device = 1;</code>
     * @param values The device to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDevice")
    public fun com.google.protobuf.kotlin.DslList<qaul.sys.ble.BleOuterClass.BleDeviceInfo, DeviceProxy>.addAll(values: kotlin.collections.Iterable<qaul.sys.ble.BleOuterClass.BleDeviceInfo>) {
      _builder.addAllDevice(values)
    }/**
     * <pre>
     * fill in a device information for each device on the system
     * </pre>
     *
     * <code>repeated .qaul.sys.ble.BleDeviceInfo device = 1;</code>
     * @param values The device to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDevice")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<qaul.sys.ble.BleOuterClass.BleDeviceInfo, DeviceProxy>.plusAssign(values: kotlin.collections.Iterable<qaul.sys.ble.BleOuterClass.BleDeviceInfo>) {
      addAll(values)
    }/**
     * <pre>
     * fill in a device information for each device on the system
     * </pre>
     *
     * <code>repeated .qaul.sys.ble.BleDeviceInfo device = 1;</code>
     * @param index The index to set the value at.
     * @param value The device to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDevice")
    public operator fun com.google.protobuf.kotlin.DslList<qaul.sys.ble.BleOuterClass.BleDeviceInfo, DeviceProxy>.set(index: kotlin.Int, value: qaul.sys.ble.BleOuterClass.BleDeviceInfo) {
      _builder.setDevice(index, value)
    }/**
     * <pre>
     * fill in a device information for each device on the system
     * </pre>
     *
     * <code>repeated .qaul.sys.ble.BleDeviceInfo device = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDevice")
    public fun com.google.protobuf.kotlin.DslList<qaul.sys.ble.BleOuterClass.BleDeviceInfo, DeviceProxy>.clear() {
      _builder.clearDevice()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.sys.ble.BleOuterClass.BleInfoResponse.copy(block: qaul.sys.ble.BleInfoResponseKt.Dsl.() -> kotlin.Unit): qaul.sys.ble.BleOuterClass.BleInfoResponse =
  qaul.sys.ble.BleInfoResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
