#!/bin/sh

# qaul.net is free software
# licensed under GPL (version 3)

## OSX installer post install step
echo "Running postinstall" > /tmp/my_postinstall.log

# no step necessary here

# return success
exit 0
