
// the configured options and settings

#define QAUL_VERSION_MAJOR @QAUL_VERSION_MAJOR@
#define QAUL_VERSION_MINOR @QAUL_VERSION_MINOR@
#define QAUL_VERSION_PATCH @QAUL_VERSION_PATCH@
#define QAUL_VERSION_SUFFIX "@QAUL_VERSION_SUFFIX@"
#define QAUL_VERSION "@QAUL_VERSION@"
#define QAUL_ROOT_PATH "@CMAKE_INSTALL_PREFIX@"
#define QAUL_DEFAULT_LOGLEVEL @QAUL_DEFAULT_LOGLEVEL@

// what are we building for?

#define QAUL_PORT_@PORT@ 1
#define QAUL_GUI_@GUI@ 1
