// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: services/group/group_net.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package qaul.net.group;

@kotlin.jvm.JvmName("-initializereplyInvite")
public inline fun replyInvite(block: qaul.net.group.ReplyInviteKt.Dsl.() -> kotlin.Unit): qaul.net.group.GroupNet.ReplyInvite =
  qaul.net.group.ReplyInviteKt.Dsl._create(qaul.net.group.GroupNet.ReplyInvite.newBuilder()).apply { block() }._build()
/**
 * ```
 * Reply to Invite
 *
 * Accept / Reject invitation
 * ```
 *
 * Protobuf type `qaul.net.group.ReplyInvite`
 */
public object ReplyInviteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: qaul.net.group.GroupNet.ReplyInvite.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: qaul.net.group.GroupNet.ReplyInvite.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): qaul.net.group.GroupNet.ReplyInvite = _builder.build()

    /**
     * ```
     * group id
     * ```
     *
     * `bytes group_id = 1;`
     */
    public var groupId: com.google.protobuf.ByteString
      @JvmName("getGroupId")
      get() = _builder.getGroupId()
      @JvmName("setGroupId")
      set(value) {
        _builder.setGroupId(value)
      }
    /**
     * ```
     * group id
     * ```
     *
     * `bytes group_id = 1;`
     */
    public fun clearGroupId() {
      _builder.clearGroupId()
    }

    /**
     * ```
     * accept true : accept, false: decline
     * ```
     *
     * `bool accept = 2;`
     */
    public var accept: kotlin.Boolean
      @JvmName("getAccept")
      get() = _builder.getAccept()
      @JvmName("setAccept")
      set(value) {
        _builder.setAccept(value)
      }
    /**
     * ```
     * accept true : accept, false: decline
     * ```
     *
     * `bool accept = 2;`
     */
    public fun clearAccept() {
      _builder.clearAccept()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun qaul.net.group.GroupNet.ReplyInvite.copy(block: qaul.net.group.ReplyInviteKt.Dsl.() -> kotlin.Unit): qaul.net.group.GroupNet.ReplyInvite =
  qaul.net.group.ReplyInviteKt.Dsl._create(this.toBuilder()).apply { block() }._build()

